"""initial schema

Revision ID: 218608bbc4b0
Revises:
Create Date: 2026-08-18 21:29:46.779967

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '218608bbc4b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_permissions',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('group', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_permissions'))
    )
    op.create_index(op.f('ix_admin_permissions_code'), 'admin_permissions', ['code'], unique=True)
    op.create_table('admin_roles',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_roles'))
    )
    op.create_index(op.f('ix_admin_roles_code'), 'admin_roles', ['code'], unique=True)
    op.create_table('admin_users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('role_code', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('is_super', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users'))
    )
    op.create_index(op.f('ix_admin_users_role_code'), 'admin_users', ['role_code'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('fee_rules',
    sa.Column('fee_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('min_fee', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('max_fee', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_rules'))
    )
    op.create_index(op.f('ix_fee_rules_fee_type'), 'fee_rules', ['fee_type'], unique=True)
    op.create_table('idempotency_records',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('business_type', sa.String(length=30), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=True),
    sa.Column('response_data', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records'))
    )
    op.create_index(op.f('ix_idempotency_records_business_type'), 'idempotency_records', ['business_type'], unique=False)
    op.create_index(op.f('ix_idempotency_records_key'), 'idempotency_records', ['key'], unique=False)
    op.create_index(op.f('ix_idempotency_records_user_id'), 'idempotency_records', ['user_id'], unique=False)
    op.create_table('matching_jobs',
    sa.Column('job_id', sa.String(length=40), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matching_jobs'))
    )
    op.create_index(op.f('ix_matching_jobs_job_id'), 'matching_jobs', ['job_id'], unique=True)
    op.create_table('membership_levels',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('benefits', sa.JSON(), nullable=False),
    sa.Column('order_limits', sa.JSON(), nullable=False),
    sa.Column('service_permissions', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership_levels')),
    sa.UniqueConstraint('code', name=op.f('uq_membership_levels_code')),
    sa.UniqueConstraint('name', name=op.f('uq_membership_levels_name'))
    )
    op.create_table('operation_logs',
    sa.Column('operator_type', sa.String(length=20), nullable=False),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('before_data', sa.Text(), nullable=False),
    sa.Column('after_data', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_logs'))
    )
    op.create_index(op.f('ix_operation_logs_action'), 'operation_logs', ['action'], unique=False)
    op.create_index(op.f('ix_operation_logs_operator_id'), 'operation_logs', ['operator_id'], unique=False)
    op.create_table('product_categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], name=op.f('fk_product_categories_parent_id_product_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_product_categories_name'))
    )
    op.create_table('promotion_rules',
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_rules'))
    )
    op.create_index(op.f('ix_promotion_rules_rule_type'), 'promotion_rules', ['rule_type'], unique=True)
    op.create_table('risk_rules',
    sa.Column('rule_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('threshold', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_rules'))
    )
    op.create_index(op.f('ix_risk_rules_rule_code'), 'risk_rules', ['rule_code'], unique=True)
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_configs'))
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('realname_status', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=False),
    sa.Column('register_ip', sa.String(length=64), nullable=False),
    sa.Column('register_channel', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('accounts',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('account_no', sa.String(length=32), nullable=False),
    sa.Column('available_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('frozen_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('pending_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_index(op.f('ix_accounts_account_no'), 'accounts', ['account_no'], unique=True)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=True)
    op.create_table('admin_role_permissions',
    sa.Column('role_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('permission_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['admin_permissions.id'], name=op.f('fk_admin_role_permissions_permission_id_admin_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], name=op.f('fk_admin_role_permissions_role_id_admin_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_admin_role_permissions_permission_id'), 'admin_role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_admin_role_permissions_role_id'), 'admin_role_permissions', ['role_id'], unique=False)
    op.create_table('admin_user_roles',
    sa.Column('admin_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name=op.f('fk_admin_user_roles_admin_id_admin_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], name=op.f('fk_admin_user_roles_role_id_admin_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_user_roles')),
    sa.UniqueConstraint('admin_id', 'role_id', name='uq_admin_user_role')
    )
    op.create_index(op.f('ix_admin_user_roles_admin_id'), 'admin_user_roles', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_user_roles_role_id'), 'admin_user_roles', ['role_id'], unique=False)
    op.create_table('announcements',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('publisher_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['admin_users.id'], name=op.f('fk_announcements_publisher_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    op.create_table('invite_codes',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('creator_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('used_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_invite_codes_creator_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], name=op.f('fk_invite_codes_used_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invite_codes'))
    )
    op.create_index(op.f('ix_invite_codes_code'), 'invite_codes', ['code'], unique=True)
    op.create_index(op.f('ix_invite_codes_creator_id'), 'invite_codes', ['creator_id'], unique=False)
    op.create_index(op.f('ix_invite_codes_status'), 'invite_codes', ['status'], unique=False)
    op.create_table('membership_orders',
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('level_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['membership_levels.id'], name=op.f('fk_membership_orders_level_id_membership_levels')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_membership_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership_orders'))
    )
    op.create_index(op.f('ix_membership_orders_order_no'), 'membership_orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_membership_orders_user_id'), 'membership_orders', ['user_id'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('level_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('level_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['membership_levels.id'], name=op.f('fk_memberships_level_id_membership_levels')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships'))
    )
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('product_no', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('service_notes', sa.Text(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('market_price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('cover', sa.String(length=255), nullable=False),
    sa.Column('images', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('service_days', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name=op.f('fk_products_category_id_product_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_product_no'), 'products', ['product_no'], unique=True)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_table('realname_verifications',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id_number', sa.String(length=128), nullable=False),
    sa.Column('document_front', sa.String(length=255), nullable=False),
    sa.Column('document_back', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_reason', sa.String(length=255), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admin_users.id'], name=op.f('fk_realname_verifications_reviewed_by_admin_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_realname_verifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_realname_verifications'))
    )
    op.create_index(op.f('ix_realname_verifications_status'), 'realname_verifications', ['status'], unique=False)
    op.create_index(op.f('ix_realname_verifications_user_id'), 'realname_verifications', ['user_id'], unique=False)
    op.create_table('risk_events',
    sa.Column('event_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rule_code', sa.String(length=40), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processed_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['processed_by'], ['admin_users.id'], name=op.f('fk_risk_events_processed_by_admin_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_risk_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_events'))
    )
    op.create_index(op.f('ix_risk_events_event_no'), 'risk_events', ['event_no'], unique=True)
    op.create_index(op.f('ix_risk_events_level'), 'risk_events', ['level'], unique=False)
    op.create_index(op.f('ix_risk_events_rule_code'), 'risk_events', ['rule_code'], unique=False)
    op.create_index(op.f('ix_risk_events_status'), 'risk_events', ['status'], unique=False)
    op.create_index(op.f('ix_risk_events_user_id'), 'risk_events', ['user_id'], unique=False)
    op.create_table('risk_users',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('last_review_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_risk_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_users'))
    )
    op.create_index(op.f('ix_risk_users_user_id'), 'risk_users', ['user_id'], unique=True)
    op.create_table('user_devices',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('device_model', sa.String(length=100), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_devices'))
    )
    op.create_index(op.f('ix_user_devices_device_id'), 'user_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('user_login_logs',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('login_type', sa.String(length=20), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('fail_reason', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_login_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_login_logs'))
    )
    op.create_index(op.f('ix_user_login_logs_user_id'), 'user_login_logs', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles'))
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('user_relation_stats',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('total_team', sa.Integer(), nullable=False),
    sa.Column('direct_count', sa.Integer(), nullable=False),
    sa.Column('active_count', sa.Integer(), nullable=False),
    sa.Column('team_order_count', sa.Integer(), nullable=False),
    sa.Column('team_order_amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_relation_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_relation_stats'))
    )
    op.create_index(op.f('ix_user_relation_stats_user_id'), 'user_relation_stats', ['user_id'], unique=False)
    op.create_table('user_relations',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('fk_user_relations_parent_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_relations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_relations'))
    )
    op.create_index(op.f('ix_user_relations_parent_id'), 'user_relations', ['parent_id'], unique=False)
    op.create_index(op.f('ix_user_relations_user_id'), 'user_relations', ['user_id'], unique=False)
    op.create_table('withdrawal_orders',
    sa.Column('withdrawal_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('fee', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('actual_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('bank_account', sa.String(length=64), nullable=False),
    sa.Column('bank_name', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('review_reason', sa.String(length=255), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admin_users.id'], name=op.f('fk_withdrawal_orders_reviewed_by_admin_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_withdrawal_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_withdrawal_orders'))
    )
    op.create_index(op.f('ix_withdrawal_orders_status'), 'withdrawal_orders', ['status'], unique=False)
    op.create_index(op.f('ix_withdrawal_orders_user_id'), 'withdrawal_orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_withdrawal_orders_withdrawal_no'), 'withdrawal_orders', ['withdrawal_no'], unique=True)
    op.create_table('account_transactions',
    sa.Column('transaction_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('business_type', sa.String(length=30), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('before_balance', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('after_balance', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('operator_type', sa.String(length=20), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_account_transactions_account_id_accounts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_account_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_transactions'))
    )
    op.create_index(op.f('ix_account_transactions_account_id'), 'account_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_transactions_business_type'), 'account_transactions', ['business_type'], unique=False)
    op.create_index(op.f('ix_account_transactions_direction'), 'account_transactions', ['direction'], unique=False)
    op.create_index(op.f('ix_account_transactions_transaction_no'), 'account_transactions', ['transaction_no'], unique=True)
    op.create_index(op.f('ix_account_transactions_user_id'), 'account_transactions', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('service_fee', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('payable_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('matched_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reservation_time', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_orders_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_order_no'), 'orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_orders_order_type'), 'orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('product_skus',
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sku_no', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('attrs', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_skus_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_skus')),
    sa.UniqueConstraint('sku_no', name=op.f('uq_product_skus_sku_no'))
    )
    op.create_index(op.f('ix_product_skus_product_id'), 'product_skus', ['product_id'], unique=False)
    op.create_table('withdrawal_logs',
    sa.Column('withdrawal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('operator_type', sa.String(length=20), nullable=False),
    sa.Column('operator_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['admin_users.id'], name=op.f('fk_withdrawal_logs_operator_id_admin_users')),
    sa.ForeignKeyConstraint(['withdrawal_id'], ['withdrawal_orders.id'], name=op.f('fk_withdrawal_logs_withdrawal_id_withdrawal_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_withdrawal_logs'))
    )
    op.create_index(op.f('ix_withdrawal_logs_withdrawal_id'), 'withdrawal_logs', ['withdrawal_id'], unique=False)
    op.create_table('appeals',
    sa.Column('appeal_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('evidence', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=255), nullable=False),
    sa.Column('processed_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_appeals_order_id_orders')),
    sa.ForeignKeyConstraint(['processed_by'], ['admin_users.id'], name=op.f('fk_appeals_processed_by_admin_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_appeals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appeals'))
    )
    op.create_index(op.f('ix_appeals_appeal_no'), 'appeals', ['appeal_no'], unique=True)
    op.create_index(op.f('ix_appeals_status'), 'appeals', ['status'], unique=False)
    op.create_index(op.f('ix_appeals_user_id'), 'appeals', ['user_id'], unique=False)
    op.create_table('buy_orders',
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('target_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('matched_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_buy_orders_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_buy_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buy_orders'))
    )
    op.create_index(op.f('ix_buy_orders_order_id'), 'buy_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_buy_orders_user_id'), 'buy_orders', ['user_id'], unique=False)
    op.create_table('fee_records',
    sa.Column('fee_no', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('fee_type', sa.String(length=30), nullable=False),
    sa.Column('base_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('fee_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_fee_records_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_records'))
    )
    op.create_index(op.f('ix_fee_records_fee_no'), 'fee_records', ['fee_no'], unique=True)
    op.create_index(op.f('ix_fee_records_fee_type'), 'fee_records', ['fee_type'], unique=False)
    op.create_index(op.f('ix_fee_records_order_id'), 'fee_records', ['order_id'], unique=False)
    op.create_table('match_logs',
    sa.Column('match_no', sa.String(length=32), nullable=False),
    sa.Column('parent_order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('operator_type', sa.String(length=20), nullable=False),
    sa.Column('operator_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['admin_users.id'], name=op.f('fk_match_logs_operator_id_admin_users')),
    sa.ForeignKeyConstraint(['parent_order_id'], ['orders.id'], name=op.f('fk_match_logs_parent_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_logs'))
    )
    op.create_index(op.f('ix_match_logs_match_no'), 'match_logs', ['match_no'], unique=False)
    op.create_index(op.f('ix_match_logs_parent_order_id'), 'match_logs', ['parent_order_id'], unique=False)
    op.create_table('match_orders',
    sa.Column('match_no', sa.String(length=32), nullable=False),
    sa.Column('parent_order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('parent_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('buyer_order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('buyer_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('seller_order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('seller_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('match_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_order_id'], ['orders.id'], name=op.f('fk_match_orders_buyer_order_id_orders')),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], name=op.f('fk_match_orders_buyer_user_id_users')),
    sa.ForeignKeyConstraint(['parent_order_id'], ['orders.id'], name=op.f('fk_match_orders_parent_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], name=op.f('fk_match_orders_parent_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_order_id'], ['orders.id'], name=op.f('fk_match_orders_seller_order_id_orders')),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], name=op.f('fk_match_orders_seller_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_orders'))
    )
    op.create_index(op.f('ix_match_orders_buyer_order_id'), 'match_orders', ['buyer_order_id'], unique=False)
    op.create_index(op.f('ix_match_orders_buyer_user_id'), 'match_orders', ['buyer_user_id'], unique=False)
    op.create_index(op.f('ix_match_orders_match_no'), 'match_orders', ['match_no'], unique=True)
    op.create_index(op.f('ix_match_orders_parent_order_id'), 'match_orders', ['parent_order_id'], unique=False)
    op.create_index(op.f('ix_match_orders_parent_user_id'), 'match_orders', ['parent_user_id'], unique=False)
    op.create_index(op.f('ix_match_orders_seller_order_id'), 'match_orders', ['seller_order_id'], unique=False)
    op.create_index(op.f('ix_match_orders_seller_user_id'), 'match_orders', ['seller_user_id'], unique=False)
    op.create_index(op.f('ix_match_orders_status'), 'match_orders', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('business_type', sa.String(length=30), nullable=False),
    sa.Column('business_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['orders.id'], name=op.f('fk_notifications_business_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sku_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products')),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], name=op.f('fk_order_items_sku_id_product_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('order_status_logs',
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=False),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('operator_type', sa.String(length=20), nullable=False),
    sa.Column('operator_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['admin_users.id'], name=op.f('fk_order_status_logs_operator_id_admin_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_status_logs_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_status_logs'))
    )
    op.create_index(op.f('ix_order_status_logs_order_id'), 'order_status_logs', ['order_id'], unique=False)
    op.create_table('promotion_records',
    sa.Column('record_no', sa.String(length=32), nullable=False),
    sa.Column('source_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('beneficiary_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('reward_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_user_id'], ['users.id'], name=op.f('fk_promotion_records_beneficiary_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_order_id'], ['orders.id'], name=op.f('fk_promotion_records_source_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.id'], name=op.f('fk_promotion_records_source_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['account_transactions.id'], name=op.f('fk_promotion_records_transaction_id_account_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_records'))
    )
    op.create_index(op.f('ix_promotion_records_beneficiary_user_id'), 'promotion_records', ['beneficiary_user_id'], unique=False)
    op.create_index(op.f('ix_promotion_records_record_no'), 'promotion_records', ['record_no'], unique=True)
    op.create_index(op.f('ix_promotion_records_source_order_id'), 'promotion_records', ['source_order_id'], unique=False)
    op.create_index(op.f('ix_promotion_records_source_user_id'), 'promotion_records', ['source_user_id'], unique=False)
    op.create_index(op.f('ix_promotion_records_status'), 'promotion_records', ['status'], unique=False)
    op.create_table('reservation_orders',
    sa.Column('reservation_no', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reserved_at', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_reservation_orders_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_reservation_orders_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reservation_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation_orders'))
    )
    op.create_index(op.f('ix_reservation_orders_order_id'), 'reservation_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_reservation_orders_reservation_no'), 'reservation_orders', ['reservation_no'], unique=True)
    op.create_index(op.f('ix_reservation_orders_user_id'), 'reservation_orders', ['user_id'], unique=False)
    op.create_table('sell_orders',
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('available_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('matched_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_sell_orders_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sell_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sell_orders'))
    )
    op.create_index(op.f('ix_sell_orders_order_id'), 'sell_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_sell_orders_user_id'), 'sell_orders', ['user_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('ticket_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_admin_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['admin_users.id'], name=op.f('fk_support_tickets_assigned_admin_id_admin_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_support_tickets_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_support_tickets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_tickets'))
    )
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_ticket_no'), 'support_tickets', ['ticket_no'], unique=True)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('appeal_logs',
    sa.Column('appeal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('operator_type', sa.String(length=20), nullable=False),
    sa.Column('operator_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['appeal_id'], ['appeals.id'], name=op.f('fk_appeal_logs_appeal_id_appeals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['admin_users.id'], name=op.f('fk_appeal_logs_operator_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appeal_logs'))
    )
    op.create_index(op.f('ix_appeal_logs_appeal_id'), 'appeal_logs', ['appeal_id'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('ticket_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', sa.String(length=500), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], name=op.f('fk_ticket_messages_ticket_id_support_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_messages'))
    )
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_appeal_logs_appeal_id'), table_name='appeal_logs')
    op.drop_table('appeal_logs')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_ticket_no'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_sell_orders_user_id'), table_name='sell_orders')
    op.drop_index(op.f('ix_sell_orders_order_id'), table_name='sell_orders')
    op.drop_table('sell_orders')
    op.drop_index(op.f('ix_reservation_orders_user_id'), table_name='reservation_orders')
    op.drop_index(op.f('ix_reservation_orders_reservation_no'), table_name='reservation_orders')
    op.drop_index(op.f('ix_reservation_orders_order_id'), table_name='reservation_orders')
    op.drop_table('reservation_orders')
    op.drop_index(op.f('ix_promotion_records_status'), table_name='promotion_records')
    op.drop_index(op.f('ix_promotion_records_source_user_id'), table_name='promotion_records')
    op.drop_index(op.f('ix_promotion_records_source_order_id'), table_name='promotion_records')
    op.drop_index(op.f('ix_promotion_records_record_no'), table_name='promotion_records')
    op.drop_index(op.f('ix_promotion_records_beneficiary_user_id'), table_name='promotion_records')
    op.drop_table('promotion_records')
    op.drop_index(op.f('ix_order_status_logs_order_id'), table_name='order_status_logs')
    op.drop_table('order_status_logs')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_match_orders_status'), table_name='match_orders')
    op.drop_index(op.f('ix_match_orders_seller_user_id'), table_name='match_orders')
    op.drop_index(op.f('ix_match_orders_seller_order_id'), table_name='match_orders')
    op.drop_index(op.f('ix_match_orders_parent_user_id'), table_name='match_orders')
    op.drop_index(op.f('ix_match_orders_parent_order_id'), table_name='match_orders')
    op.drop_index(op.f('ix_match_orders_match_no'), table_name='match_orders')
    op.drop_index(op.f('ix_match_orders_buyer_user_id'), table_name='match_orders')
    op.drop_index(op.f('ix_match_orders_buyer_order_id'), table_name='match_orders')
    op.drop_table('match_orders')
    op.drop_index(op.f('ix_match_logs_parent_order_id'), table_name='match_logs')
    op.drop_index(op.f('ix_match_logs_match_no'), table_name='match_logs')
    op.drop_table('match_logs')
    op.drop_index(op.f('ix_fee_records_order_id'), table_name='fee_records')
    op.drop_index(op.f('ix_fee_records_fee_type'), table_name='fee_records')
    op.drop_index(op.f('ix_fee_records_fee_no'), table_name='fee_records')
    op.drop_table('fee_records')
    op.drop_index(op.f('ix_buy_orders_user_id'), table_name='buy_orders')
    op.drop_index(op.f('ix_buy_orders_order_id'), table_name='buy_orders')
    op.drop_table('buy_orders')
    op.drop_index(op.f('ix_appeals_user_id'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_status'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_appeal_no'), table_name='appeals')
    op.drop_table('appeals')
    op.drop_index(op.f('ix_withdrawal_logs_withdrawal_id'), table_name='withdrawal_logs')
    op.drop_table('withdrawal_logs')
    op.drop_index(op.f('ix_product_skus_product_id'), table_name='product_skus')
    op.drop_table('product_skus')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_type'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_no'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_account_transactions_user_id'), table_name='account_transactions')
    op.drop_index(op.f('ix_account_transactions_transaction_no'), table_name='account_transactions')
    op.drop_index(op.f('ix_account_transactions_direction'), table_name='account_transactions')
    op.drop_index(op.f('ix_account_transactions_business_type'), table_name='account_transactions')
    op.drop_index(op.f('ix_account_transactions_account_id'), table_name='account_transactions')
    op.drop_table('account_transactions')
    op.drop_index(op.f('ix_withdrawal_orders_withdrawal_no'), table_name='withdrawal_orders')
    op.drop_index(op.f('ix_withdrawal_orders_user_id'), table_name='withdrawal_orders')
    op.drop_index(op.f('ix_withdrawal_orders_status'), table_name='withdrawal_orders')
    op.drop_table('withdrawal_orders')
    op.drop_index(op.f('ix_user_relations_user_id'), table_name='user_relations')
    op.drop_index(op.f('ix_user_relations_parent_id'), table_name='user_relations')
    op.drop_table('user_relations')
    op.drop_index(op.f('ix_user_relation_stats_user_id'), table_name='user_relation_stats')
    op.drop_table('user_relation_stats')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_login_logs_user_id'), table_name='user_login_logs')
    op.drop_table('user_login_logs')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_device_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_risk_users_user_id'), table_name='risk_users')
    op.drop_table('risk_users')
    op.drop_index(op.f('ix_risk_events_user_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_status'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_rule_code'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_level'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_event_no'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_realname_verifications_user_id'), table_name='realname_verifications')
    op.drop_index(op.f('ix_realname_verifications_status'), table_name='realname_verifications')
    op.drop_table('realname_verifications')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_product_no'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_membership_orders_user_id'), table_name='membership_orders')
    op.drop_index(op.f('ix_membership_orders_order_no'), table_name='membership_orders')
    op.drop_table('membership_orders')
    op.drop_index(op.f('ix_invite_codes_status'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_creator_id'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_admin_user_roles_role_id'), table_name='admin_user_roles')
    op.drop_index(op.f('ix_admin_user_roles_admin_id'), table_name='admin_user_roles')
    op.drop_table('admin_user_roles')
    op.drop_index(op.f('ix_admin_role_permissions_role_id'), table_name='admin_role_permissions')
    op.drop_index(op.f('ix_admin_role_permissions_permission_id'), table_name='admin_role_permissions')
    op.drop_table('admin_role_permissions')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_no'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_risk_rules_rule_code'), table_name='risk_rules')
    op.drop_table('risk_rules')
    op.drop_index(op.f('ix_promotion_rules_rule_type'), table_name='promotion_rules')
    op.drop_table('promotion_rules')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_operation_logs_operator_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_action'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_table('membership_levels')
    op.drop_index(op.f('ix_matching_jobs_job_id'), table_name='matching_jobs')
    op.drop_table('matching_jobs')
    op.drop_index(op.f('ix_idempotency_records_user_id'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_key'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_business_type'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_fee_rules_fee_type'), table_name='fee_rules')
    op.drop_table('fee_rules')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_role_code'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_admin_roles_code'), table_name='admin_roles')
    op.drop_table('admin_roles')
    op.drop_index(op.f('ix_admin_permissions_code'), table_name='admin_permissions')
    op.drop_table('admin_permissions')
    # ### end Alembic commands ###
